In [1]:
import numpy as np

In [ ]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

Original 10x10 Array:
[[52 93 15 72 61 21 83 87 75 75]
 [88 24  3 22 53  2 88 30 38  2]
 [64 60 21 33 76 58 22 89 49 91]
 [59 42 92 60 80 15 62 62 47 62]
 [51 55 64  3 51  7 21 73 39 18]
 [ 4 89 60 14  9 90 53  2 84 92]
 [60 71 44  8 47 35 78 81 36 50]
 [ 4  2  6 54  4 54 93 63 18 90]
 [44 34 74 62 14 95 48 15 72 78]
 [87 62 40 85 80 82 53 24 26 89]]


Array A (5x7):
[[52 93 15 72 61 21 83]
 [88 24  3 22 53  2 88]
 [64 60 21 33 76 58 22]
 [59 42 92 60 80 15 62]
 [51 55 64  3 51  7 21]]
Shape of A: (5, 7)

Array B (7x5):
[[52 93 15 72 61]
 [88 24  3 22 53]
 [64 60 21 33 76]
 [59 42 92 60 80]
 [51 55 64  3 51]
 [ 4 89 60 14  9]
 [60 71 44  8 47]]
Shape of B: (7, 5)

Array C (5x7):
[[72 61 21 83 87 75 75]
 [22 53  2 88 30 38  2]
 [33 76 58 22 89 49 91]
 [60 80 15 62 62 47 62]
 [ 3 51  7 21 73 39 18]]
Shape of C: (5, 7)

Sum of A and C (A + C):
[[124 154  36 155 148  96 158]
 [110  77   5 110  83  40  90]
 [ 97 136  79  55 165 107 113]
 [119 122 107 122 142  62 124]
 [ 54 106  71  24 124  

In [3]:
# Create a 10x10 array with random values
original_array = np.random.randint(1, 100, size=(10, 10))
print("Original 10x10 Array:")
print(original_array)
print("\n" + "="*50 + "\n")

# Slice array A (5x7) - rows 0-4, columns 0-6
A = original_array[0:5, 0:7]
print("Array A (5x7):")
print(A)
print(f"Shape of A: {A.shape}\n")

# Slice array B (7x5) - rows 0-6, columns 0-4
B = original_array[0:7, 0:5]
print("Array B (7x5):")
print(B)
print(f"Shape of B: {B.shape}\n")

# Slice array C (5x7) - rows 0-4, columns 3-9
C = original_array[0:5, 3:10]
print("Array C (5x7):")
print(C)
print(f"Shape of C: {C.shape}\n")

# Sum of A and C (same shape: 5x7)
sum_AC = A + C
print("Sum of A and C (A + C):")
print(sum_AC)
print(f"Shape of sum: {sum_AC.shape}\n")

# Multiplication of A and B (5x7) * (7x5) = (5x5)
try:
    product_AB = np.dot(A, B)
    print("Multiplication of A and B (Matrix Multiplication):")
    print(product_AB)
    print(f"Shape of product: {product_AB.shape}")
except ValueError as e:
    print(f"Error in multiplication: {e}")

Original 10x10 Array:
[[60 41 29 15 45 65 89 71  9 88]
 [ 1  8 88 63 11 81  8 35 35 33]
 [ 5 41 28  7 73 72 12 34 33 48]
 [23 62 88 37 99 44 86 91 35 65]
 [99 47 78  3  1  5 90 14 27  9]
 [79 15 90 42 77 51 63 96 52 96]
 [ 4 94 23 15 43 29 36 13 32 71]
 [59 86 28 66 42 45 62 57  6 28]
 [28 44 84 30 62 75 92 89 62 97]
 [ 1 27 62 77  3 70 72 27  9 62]]


Array A (5x7):
[[60 41 29 15 45 65 89]
 [ 1  8 88 63 11 81  8]
 [ 5 41 28  7 73 72 12]
 [23 62 88 37 99 44 86]
 [99 47 78  3  1  5 90]]
Shape of A: (5, 7)

Array B (7x5):
[[60 41 29 15 45]
 [ 1  8 88 63 11]
 [ 5 41 28  7 73]
 [23 62 88 37 99]
 [99 47 78  3  1]
 [79 15 90 42 77]
 [ 4 94 23 15 43]]
Shape of B: (7, 5)

Array C (5x7):
[[15 45 65 89 71  9 88]
 [63 11 81  8 35 35 33]
 [ 7 73 72 12 34 33 48]
 [37 99 44 86 91 35 65]
 [ 3  1  5 90 14 27  9]]
Shape of C: (5, 7)

Sum of A and C (A + C):
[[ 75  86  94 104 116  74 177]
 [ 64  19 169  71  46 116  41]
 [ 12 114 100  19 107 105  60]
 [ 60 161 132 123 190  79 151]
 [102  48  83  93  15  